-- **************************** SqlDBM: MySQL ***************************
-- **** Generated by SqlDBM: ResourceGuard by solomonf1227@gmail.com ****


-- ************************************** `Employee`

CREATE TABLE `Employee`
(
 `id`        int NOT NULL ,
 `firstName` varchar(60) NOT NULL ,
 `lastName`  varchar(60) NOT NULL ,
 `role`      varchar(60) NOT NULL ,
 `email`     varchar(60) NULL ,
 `phone`     varchar(20) NULL ,
 `salary`    decimal(10, 2) NOT NULL ,
 `dateHired` date NOT NULL ,

PRIMARY KEY (`id`)
);

-- ************************************** `Payroll`

CREATE TABLE `Payroll`
(
 `id`             int NOT NULL ,
 `totalWorkHours` decimal(4, 2) NOT NULL ,
 `salary`         decimal(10, 2) NOT NULL ,
 `netSalary`      decimal(10, 2) NOT NULL ,
 `paymentDate`    date NOT NULL ,
 `empolyeeId`     int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`empolyeeId`),
CONSTRAINT `FK_2` FOREIGN KEY `FK_1` (`empolyeeId`) REFERENCES `Employee` (`id`)
);

-- ************************************** `Attendance`

CREATE TABLE `Attendance`
(
 `id`              int NOT NULL ,
 `CheckInTime`     datetime NOT NULL ,
 `CheckOutTime`    datetime NOT NULL ,
 `totalkWorkHours` decimal(4, 2) NOT NULL ,
 `attendanceDate`  date NOT NULL ,
 `status`          boolean NOT NULL ,
 `employeeId`      int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`employeeId`),
CONSTRAINT `FK_9_1` FOREIGN KEY `FK_1` (`employeeId`) REFERENCES `Employee` (`id`)
);


-- ************************************** `Catagory`

CREATE TABLE `Catagory`
(
 `id`           int NOT NULL ,
 `catagoryName` varchar(60) NOT NULL ,
 `createdAt`    datetime NOT NULL ,
 `updatedAt`    datetime NOT NULL ,

PRIMARY KEY (`id`)
);

-- ************************************** `Product`

CREATE TABLE `Product`
(
 `id`             int NOT NULL ,
 `ProductName`    varchar(60) NOT NULL ,
 `productType`    varchar(60) NOT NULL ,
 `quantity`       int NOT NULL ,
 `price`          decimal(10, 2) NOT NULL ,
 `productionDate` datetime NOT NULL ,
 `createdAt`      datetime NOT NULL ,
 `updatedAt`      datetime NOT NULL ,
 `catagoryId`     int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`catagoryId`),
CONSTRAINT `FK_4` FOREIGN KEY `FK_1` (`catagoryId`) REFERENCES `Catagory` (`id`)
);

-- ************************************** `Inventory`

CREATE TABLE `Inventory`
(
 `id`              int NOT NULL ,
 `itemType`        enum NOT NULL ,
 `quantityInStock` bigint NOT NULL ,
 `updatedAt`       datetime NOT NULL ,
 `productId`       int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`productId`),
CONSTRAINT `FK_3` FOREIGN KEY `FK_1` (`productId`) REFERENCES `Product` (`id`)
);


-- ************************************** `Supplier`

CREATE TABLE `Supplier`
(
 `id`          int NOT NULL ,
 `name`        varchar(60) NOT NULL ,
 `contactInfo` varchar(60) NOT NULL ,
 `email`       varchar(60) NOT NULL ,
 `address`     varchar(200) NOT NULL ,

PRIMARY KEY (`id`)
);


-- ************************************** `RawMaterial`

CREATE TABLE `RawMaterial`
(
 `id`           int NOT NULL ,
 `materialName` varchar(60) NOT NULL ,
 `quantity`     int NOT NULL ,
 `unitPrice`    decimal(15, 2) NOT NULL ,
 `createdAt`    datetime NOT NULL ,
 `updatedAt`    datetime NOT NULL ,
 `supplierId`   int NOT NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`supplierId`),
CONSTRAINT `FK_5` FOREIGN KEY `FK_1` (`supplierId`) REFERENCES `Supplier` (`id`)
);



-- ************************************** `Transaction`

CREATE TABLE `Transaction`
(
 `id`                     int NOT NULL ,
 `itemType`               enum('rawmaterial', 'product') NOT NULL ,
 `transactionType`        enum('add', 'withdraw') NOT NULL ,
 `quantity`               int NOT NULL ,
 `transactionDate`        datetime NOT NULL ,
 `transactionByEmployeId` int NOT NULL ,
 `productId`              int NULL ,
 `rawMaterialId`          int NULL ,

PRIMARY KEY (`id`),
KEY `FK_1` (`transactionByEmployeId`),
CONSTRAINT `FK_7` FOREIGN KEY `FK_1` (`transactionByEmployeId`) REFERENCES `Employee` (`id`),
KEY `FK_2` (`productId`),
CONSTRAINT `FK_8` FOREIGN KEY `FK_2` (`productId`) REFERENCES `Product` (`id`),
KEY `FK_3` (`rawMaterialId`),
CONSTRAINT `FK_9` FOREIGN KEY `FK_3` (`rawMaterialId`) REFERENCES `RawMaterial` (`id`)
);
